---
- hosts: webservers
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
 
    - name: enabled mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
         - restart apache2
    
    - name: Copy Index page
      copy:
        src: /home/rohinijadhav587/ansible-demo/indextest.html
        dest: /var/www/html/indextest.html

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
